# ExtensionConfig for registering Runtime Extension in CAPI
# This is the most important resource - it registers VIP Allocator as a Runtime Extension
apiVersion: runtime.cluster.x-k8s.io/v1alpha1
kind: ExtensionConfig
metadata:
  name: vip-allocator
  namespace: capi-system
  labels:
    cluster.x-k8s.io/provider: vip-allocator
  annotations:
    # IMPORTANT: This annotation tells CAPI controller-manager to automatically
    # inject CA bundle from certificate into spec.clientConfig.caBundle
    cert-manager.io/inject-ca-from: capi-system/capi-vip-allocator-runtime-extension-cert
spec:
  clientConfig:
    # Configuration for connecting to Runtime Extension
    service:
      name: capi-vip-allocator-runtime-extension
      namespace: capi-system
      port: 443
    # caBundle will be automatically populated by CAPI controller-manager
    # thanks to cert-manager.io/inject-ca-from annotation
    # caBundle: <will be injected automatically>
  
  # Namespace selector where the extension will operate
  # Empty object {} means "all namespaces"
  namespaceSelector: {}

# Settings for Runtime Extension (optional)
# Additional configuration parameters can be passed here
settings: {}
