apiVersion: v1
kind: Service
metadata:
  name: capi-vip-allocator-controller-manager-metrics-service
  labels:
    control-plane: capi-vip-allocator-controller-manager
spec:
  selector:
    control-plane: capi-vip-allocator-controller-manager
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
