apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capi-vip-allocator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capi-vip-allocator-manager-role
subjects:
  - kind: ServiceAccount
    name: capi-vip-allocator-controller-manager
    namespace: capi-vip-allocator-system
