apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-vip-allocator-manager-role
rules:
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusters
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusters/status
    verbs:
      - get
  - apiGroups:
      - ipam.cluster.x-k8s.io
    resources:
      - globalinclusterippools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ipam.cluster.x-k8s.io
    resources:
      - ipaddressclaims
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ipam.cluster.x-k8s.io
    resources:
      - ipaddresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
