apiVersion: runtime.cluster.x-k8s.io/v1alpha1
kind: ExtensionConfig
metadata:
  name: vip-allocator
  namespace: capi-system
  labels:
    cluster.x-k8s.io/provider: vip-allocator
  annotations:
    cert-manager.io/inject-ca-from: capi-system/capi-vip-allocator-runtime-extension-cert
spec:
  clientConfig:
    service:
      name: capi-vip-allocator-runtime-extension
      namespace: capi-system
      port: 443
    # caBundle will be injected by cert-manager
  namespaceSelector: {}
settings:
  {}

