# Example: Cluster with manually specified VIP
#
# Runtime Extension will skip automatic allocation when
# controlPlaneEndpoint.host is already set.
#
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: example-manual-vip
  namespace: default
spec:
  controlPlaneEndpoint:
    host: "10.0.0.100"
    port: 6443
  topology:
    class: my-cluster-class
    version: v1.30.0
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
        - class: default-worker
          name: workers
          replicas: 2
