name: Create Draft Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # Allow creating a release.
  packages: write # Allow publishing container images.

jobs:
  draft_release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/gorizond/capi-vip-allocator
    steps:
      # - name: Set env
      #   run:  echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Checkout the Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE }}:${{ github.ref_name }}
            ${{ env.IMAGE }}:latest
      # - name: generate release notes
      #   run: |
      #     make release-notes
      - name: Create Release Artifacts
        run: make release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: out/*.*
